---
sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.4
- 2.3.6
addons:
  postgresql: '9.5'
env:
  global:
  - DATABASE_URL="postgresql://postgres:@localhost:5432/topological_inventory_core_test?encoding=utf8&pool=5&wait_timeout=5"
before_install:
- gem install bundler -v 1.16.4
before_script:
- bundle exec rake spec:setup
