default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: root
  wait_timeout: 5
  min_messages: warning
  host: localhost
  port: 5432

development:
  <<: *default
  database: topological_inventory_core_development

test:
  <<: *default
  database: topological_inventory_core_test

production:
  <<: *default
  database: topological_inventory_core_production
