# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09174f007648455d512e717d21064bd928c9d13ea308755183c9401b57cdcda61e0e4b771487744b2427d3864b8cbbd41c70f543f31f2132cd6892da21a61e76

test:
  secret_key_base: 30ed56cd9cc5b7451b94da6fc66a5d7ec6715a9914265f5e4766ed9f21a11b9b9598aa6ed9455b6cf3ab3f4b907693a0dcf1457d6e50cc4baa7cd06505b1a810

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
